package co.ar_smart.www.endpoints;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.v4.content.ContextCompat;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.TextView;

import java.util.ArrayList;

import co.ar_smart.www.living.HomeActivity;
import co.ar_smart.www.living.R;
import co.ar_smart.www.pojos.Endpoint;

import static co.ar_smart.www.helpers.Constants.ACTION_EDIT;
import static co.ar_smart.www.helpers.Constants.EXTRA_ACTION;
import static co.ar_smart.www.helpers.Constants.EXTRA_CATEGORY_DEVICE;
import static co.ar_smart.www.helpers.Constants.EXTRA_LIST_PARCELABLE_FIRST;
import static co.ar_smart.www.helpers.Constants.EXTRA_MESSAGE;
import static co.ar_smart.www.helpers.Constants.EXTRA_MESSAGE_PREF_HUB;
import static co.ar_smart.www.helpers.Constants.EXTRA_OBJECT;
import static co.ar_smart.www.helpers.Constants.EXTRA_UID;

public class DevicesActivity extends AppCompatActivity {

    /**
     * Token generated by JWT
     */
    private String API_TOKEN = "";
    /**
     * Endpoints list
     */
    private ArrayList<Endpoint> devices;

    /**
     * Represent the list view where the devices will be shown
     */
    private ListView lista;
    /**
     * Represent the progress circle shown while the devices are been downloaded
     */
    private ProgressBar progress;
    /**
     * Represent the current instance
     */
    private Activity myact;
    private int PREFERRED_HUB_ID;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_devices);
        devices=new ArrayList<>();
        myact=this;


        lista = (ListView) findViewById(R.id.list_DevicesHub);
        progress = (ProgressBar) findViewById(R.id.progressDevices);


        if (getSupportActionBar() != null) {
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
            getSupportActionBar().setHomeButtonEnabled(true);
            getSupportActionBar().setTitle(getString(R.string.label_devices_activity_title));
        }

        Intent intent = getIntent();
        API_TOKEN = intent.getStringExtra(EXTRA_MESSAGE);
        devices = intent.getParcelableArrayListExtra(EXTRA_OBJECT);
        PREFERRED_HUB_ID = intent.getIntExtra(EXTRA_MESSAGE_PREF_HUB, -1);
        for (int i = 0; i < devices.size(); i++) {
            Log.d("DISPOSITIVO", devices.get(i).toString());
        }

        lista.setAdapter(new ArrayAdapter<Endpoint>(DevicesActivity.this, android.R.layout.simple_list_item_1, devices) {
            @NonNull
            @Override
            public View getView(int position, View convertView, @NonNull ViewGroup parent) {
                View view = convertView;
                if (view == null) {
                    view = getLayoutInflater().inflate(R.layout.row_list_devices, null);
                }
                TextView device_name = (TextView) view.findViewById(R.id.nameDeviceEdit);
                TextView category_name = (TextView) view.findViewById(R.id.nameCategoryEdit);
                ImageView i = (ImageView) view.findViewById(R.id.iconEdit);
                device_name.setText(devices.get(position).getName());
                category_name.setText(devices.get(position).getCategory().getCat());
                i.setImageDrawable(ContextCompat.getDrawable(myact, R.drawable.edit_mode));
                //chk.setChecked(checked[position]);
                return view;
            }
        });
        lista.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {

                Intent intent = new Intent(DevicesActivity.this, EditDeviceActivity.class);
                Bundle bundle = new Bundle();
                bundle.putParcelable(EXTRA_OBJECT, devices.get(position));
                intent.putExtras(bundle);
                intent.putExtra(EXTRA_CATEGORY_DEVICE, devices.get(position).getCategory());
                intent.putExtra(EXTRA_MESSAGE, API_TOKEN);
                intent.putExtra(EXTRA_ACTION, ACTION_EDIT);
                intent.putParcelableArrayListExtra(EXTRA_LIST_PARCELABLE_FIRST, devices);
                intent.putExtra(EXTRA_UID, String.valueOf(devices.get(position).getId()));
                intent.putExtra(EXTRA_MESSAGE_PREF_HUB, PREFERRED_HUB_ID);
                startActivityForResult(intent, HomeActivity.ACTIVITY_CODE_ENDPOINT);
            }
        });

        progress.setVisibility(View.GONE);
        lista.setVisibility(View.VISIBLE);
    }





    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                // app icon in action bar clicked; go home
                this.finish();
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        // Check which request we're responding to
        if (requestCode == HomeActivity.ACTIVITY_CODE_ENDPOINT) {
            // Make sure the request was successful
            if (resultCode == RESULT_OK) {
                Intent intent = new Intent();
                intent.putExtra(EXTRA_OBJECT, data.getExtras().getParcelable(EXTRA_OBJECT));
                setResult(RESULT_OK, intent);
                finish();//finishing activity
            }
        }
    }


}
