package co.ar_smart.www.endpoints;

import android.content.Intent;
import android.graphics.drawable.AnimationDrawable;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.MenuItem;
import android.view.View;
import android.widget.ImageView;

import java.util.ArrayList;

import co.ar_smart.www.living.R;
import co.ar_smart.www.pojos.Endpoint;

import static co.ar_smart.www.helpers.Constants.EXTRA_MESSAGE;
import static co.ar_smart.www.helpers.Constants.EXTRA_MESSAGE_PREF_HUB;
import static co.ar_smart.www.helpers.Constants.EXTRA_OBJECT;
import static co.ar_smart.www.helpers.Constants.EXTRA_TYPE_DEVICE;
import static co.ar_smart.www.helpers.Constants.TYPE_DEVICE_WIFI;
import static co.ar_smart.www.helpers.Constants.TYPE_DEVICE_ZWAVE;

public class ManagementEndpointsActivity extends AppCompatActivity {

    /**
     * Token generated by JWT
     */
    private String API_TOKEN;
    private int PREFERRED_HUB_ID;
    private ArrayList<Endpoint> endpoints = new ArrayList<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_management_endpoint);
        if (getSupportActionBar() != null) {
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
            getSupportActionBar().setTitle(getString(R.string.label_devices_activity_title));
        }

        API_TOKEN = getIntent().getStringExtra(EXTRA_MESSAGE);
        PREFERRED_HUB_ID = getIntent().getIntExtra(EXTRA_MESSAGE_PREF_HUB, -1);
        endpoints = getIntent().getParcelableArrayListExtra(EXTRA_OBJECT);
        ImageView img = (ImageView)findViewById(R.id.imgAni);
        img.setBackgroundResource(R.drawable.basic_animation);

        // Get the background, which has been compiled to an AnimationDrawable object.
        AnimationDrawable frameAnimation = (AnimationDrawable) img.getBackground();

        // Start the animation (looped playback by default).
        frameAnimation.start();
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                // app icon in action bar clicked; go home
                //TODO set result
                this.finish();
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

    /**
     * Open add wifi activity
     */
    public void addWifi(View v)
    {
        Intent i=new Intent(ManagementEndpointsActivity.this,NewDevicesActivity.class);
        i.putExtra(EXTRA_TYPE_DEVICE,TYPE_DEVICE_WIFI);
        i.putExtra(EXTRA_MESSAGE, API_TOKEN);
        i.putExtra(EXTRA_MESSAGE_PREF_HUB, PREFERRED_HUB_ID);
        startActivity(i);
    }

    /**
     * Open add zwave activity
     */
    public void addZWave(View v)
    {
        Intent i=new Intent(ManagementEndpointsActivity.this,NewDevicesActivity.class);
        i.putExtra(EXTRA_TYPE_DEVICE,TYPE_DEVICE_ZWAVE);
        i.putExtra(EXTRA_MESSAGE, API_TOKEN);
        i.putExtra(EXTRA_MESSAGE_PREF_HUB, PREFERRED_HUB_ID);
        startActivity(i);
    }

    /**
     * Open delete wifi device activity
     */
    public void delWifi(View v)
    {
        Intent i=new Intent(ManagementEndpointsActivity.this,DeleteDeviceActivity.class);
        i.putExtra(EXTRA_TYPE_DEVICE,TYPE_DEVICE_WIFI);
        i.putExtra(EXTRA_MESSAGE, API_TOKEN);
        i.putExtra(EXTRA_MESSAGE_PREF_HUB, PREFERRED_HUB_ID);
        i.putParcelableArrayListExtra(EXTRA_OBJECT, endpoints);
        startActivity(i);
    }

    /**
     * Open delete zwave device activity
     */
    public void delZWave(View v)
    {
        Intent i=new Intent(ManagementEndpointsActivity.this,DeleteZwaveActivity.class);
        i.putExtra(EXTRA_TYPE_DEVICE,TYPE_DEVICE_ZWAVE);
        i.putExtra(EXTRA_MESSAGE, API_TOKEN);
        i.putExtra(EXTRA_MESSAGE_PREF_HUB, PREFERRED_HUB_ID);
        i.putParcelableArrayListExtra(EXTRA_OBJECT, endpoints);
        startActivity(i);
    }

    /**
     * Open edit devices activity
     */
    public void editDevices(View v)
    {
        Intent intent = new Intent(ManagementEndpointsActivity.this, DevicesActivity.class);
        intent.putExtra(EXTRA_MESSAGE, API_TOKEN);
        intent.putExtra(EXTRA_MESSAGE_PREF_HUB, PREFERRED_HUB_ID);
        startActivity(intent);
    }
}
